Repository twitterdev/twitter-ruby-ads-sdk, pull requests merged in 2019-06, with the labels that each got.

#195 Add ActiveEntities support
  examples/active_entities.rb
  lib/twitter-ads.rb
  lib/twitter-ads/campaign/campaign.rb
  lib/twitter-ads/campaign/funding_instrument.rb
  lib/twitter-ads/campaign/line_item.rb
  lib/twitter-ads/campaign/organic_tweet.rb
  lib/twitter-ads/campaign/tweet.rb
  lib/twitter-ads/creative/media_creative.rb
  lib/twitter-ads/creative/promoted_account.rb
  lib/twitter-ads/creative/promoted_tweet.rb
  lib/twitter-ads/resources/analytics.rb
Labels: task

#194 Add new preview endpoint support
  examples/tweet_previews.rb
  lib/twitter-ads.rb
  lib/twitter-ads/creative/tweet_previews.rb
  lib/twitter-ads/enum.rb
Labels: task

#197 Minor bug fixes
  examples/promoted_tweet.rb
  lib/twitter-ads/creative/cards_fetch.rb
Labels: bug

#196 Improve Travis CI Tests
  .rubocop.yml
  .travis.yml
  README.md
  twitter-ads.gemspec
Labels: code-quality

#198 Update twitter-ads version to 5.1.0
  lib/twitter-ads/version.rb
Labels: task

#176 Rename user_ids to user_id in Account#timeline
  lib/twitter-ads/account.rb
Labels: bug, task

#201 [Bug] Fix string concatenation
  .hound.yml
  examples/active_entities.rb
  examples/tailored_audience.rb
  lib/twitter-ads/audiences/tailored_audience.rb
Labels: bug

#202 Add support for Tailored Audience Permissions
  examples/audience_permissions.rb
  lib/twitter-ads/audiences/tailored_audience.rb
  lib/twitter-ads/version.rb
Labels: task

#203 Add conversation targeting, minor fixes
  lib/twitter-ads/settings/tax.rb
  lib/twitter-ads/targeting_criteria/conversation.rb
Labels: bug, task
